# Generated by Django 5.2.6 on 2026-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_safetrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetrip',
            name='danger_zones',
            field=models.TextField(blank=True, help_text='List of identified risky areas or factors'),
        ),
        migrations.AddField(
            model_name='safetrip',
            name='safety_recommendations',
            field=models.TextField(blank=True, help_text='Suggestions for a safer journey'),
        ),
    ]
