# Generated by Django 5.2.6 on 2026-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_safetrip_danger_zones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('theft', 'Theft/Robbery'), ('harassment', 'Harassment'), ('lighting', 'Poor Lighting'), ('accident', 'Accident'), ('other', 'Other')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
