# Generated by Django 5.2.6 on 2026-02-15 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_redeemedreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('issue_category', models.CharField(choices=[('lighting', 'Poor Lighting'), ('safety', 'Safety Concern'), ('traffic', 'Heavy Traffic'), ('road', 'Bad Road Quality'), ('isolated', 'Isolated Area'), ('other', 'Other')], max_length=20)),
                ('what_went_wrong', models.TextField(help_text='Describe the bad experience you had')),
                ('suggested_alternative', models.TextField(help_text='Suggest a better or safer route for others')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
