# Generated by Django 5.2.6 on 2026-02-15 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_routefeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('lighting_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='How well-lit was the route?')),
                ('crowd_level', models.CharField(choices=[('empty', 'Empty/Deserted'), ('few', 'Few People'), ('moderate', 'Moderately Crowded'), ('crowded', 'Very Crowded')], help_text='How crowded was the route?', max_length=20)),
                ('experienced_harassment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Did you experience any harassment?', max_length=3)),
                ('harassment_details', models.TextField(blank=True, help_text='If yes, please describe (optional)')),
                ('experienced_teasing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Did you experience catcalling or teasing?', max_length=3)),
                ('teasing_details', models.TextField(blank=True, help_text='If yes, please describe (optional)')),
                ('felt_unsafe', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Did you feel unsafe at any point?', max_length=3)),
                ('unsafe_details', models.TextField(blank=True, help_text='If yes, please describe what made you feel unsafe (optional)')),
                ('overall_safety_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Overall, how safe did you feel on this route?')),
                ('additional_comments', models.TextField(blank=True, help_text='Any other feedback or suggestions?')),
                ('time_of_travel', models.CharField(choices=[('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)'), ('night', 'Night (8 PM - 6 AM)')], help_text='When did you travel?', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.safetrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Survey',
                'verbose_name_plural': 'Safety Surveys',
            },
        ),
    ]
